title: Arsenal
# author:
#   name: Leonard Ngo
#   email: "lordknight1904@gmail.com"

webmentions:
  debug: true

theme: minima
# timezone: KR
# google_analytics: UA-NNNNNNNN-N
# minima:
#   skin: dark

# plugins:
#   - jekyll-seo-tag
