title: Arsenal
author:
  name: Leonard Ngo
  email: "lordknight1904@gmail.com"

theme: minima
timezone: KR
# google_analytics: UA-NNNNNNNN-N
minima:
  skin: auto

plugins:
  - jekyll-seo-tag

header_pages:
  - about.md